version: "3.1"
services:
  # 主容器
  web:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  # web操作数据库
  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
    depends_on:
      - db
  # MySQL5.7及以上版本
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: csdn-exam-c4-javabase
      MYSQL_USER: csdn-exam-c4-javabase
      MYSQL_PASSWORD: csdn-exam-c4-javabase
      MYSQL_RANDOM_ROOT_PASSWORD: yes
