spring:
  datasource:
    url: jdbc:mysql://mysql57:3306/content?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    username: root
    password: c4_project_exam
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database-platform: net.csdn.ac.c4.exam.config.MysqlConfig # 如不设置默认使用MyISAM引擎，将不能创建外键
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: net.csdn.ac.c4.exam.config.C4PhysicalNamingStrategy
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true
  sql:
    init:
      mode: always