version: '3.1'
services:
    redis:
        image: 'redis:alpine'

    frontend:
      image: 'nginx:alpine'
      working_dir: /usr/share/nginx/html
      volumes:
        - './frontend_server/dist.conf:/etc/nginx/conf.d/default.conf'
        - './frontend_server/dist:/usr/share/nginx/html/dist'
      ports:
        - '9528:80'

